site_name: napari-sim-contrast
site_description: A plugin to estimate the contrast and phase of SIM images.
site_author: Andrea Bassi and Paolo Maran

theme: readthedocs

repo_url: https://github.com/GiorgiaTortora/napari-sim-contrast

pages:
- Home: index.md
